Feature/add trapi validator to test suite
NCATS-Tangerine/icees-api pull request #129
Opened 2021-06-14 18:32 UTC by xu-hao

2021-06-14 20:26 UTC, patrickkwang requested changes

2021-06-14 20:26 UTC, patrickkwang commented on icees_api/features/knowledgegraph.py
> +    try:
I'd like to find a cleaner way to catch errors than a 100-line-long try..except block. Have we tried FastAPI's exception handler? https://fastapi.tiangolo.com/tutorial/handling-errors/#install-custom-exception-handlers

2021-06-14 20:26 UTC, patrickkwang commented on icees_api/features/knowledgegraph.py
> +def knowledge_graph_node_trapi_1_1(node_name, table, filter_regex, biolink_classes):
Why are these necessary? The commit message just says "trapi validate".

2021-06-16 19:55 UTC, xu-hao reviewed
Can we merge this?

2021-06-17 18:53 UTC, patrickkwang requested changes

2021-06-18 01:59 UTC, patrickkwang approved these changes

2021-06-18 15:06 UTC, merged